name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore src/BillingGateway.sln
      
    - name: Build solution
      run: dotnet build src/BillingGateway.sln --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test src/BillingGateway.sln --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: success()
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false
        
    - name: Build failure notification
      if: failure()
      run: |
        echo "::error::Build or tests failed. Please check the logs above."
        exit 1

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Run security scan
      run: |
        dotnet tool install --global security-scan
        security-scan src/BillingGateway.sln --ignore-msbuild-errors
      continue-on-error: true

  quality-gate:
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    if: always()
    
    steps:
    - name: Quality Gate
      run: |
        if [ "${{ needs.build-and-test.result }}" != "success" ]; then
          echo "::error::Quality gate failed: Build and tests must pass"
          exit 1
        fi
        echo "::notice::Quality gate passed: All checks successful"